"""Viewer-availability banner in the static report (v0.6.x ERR_CONNECTION_REFUSED fix)."""
from __future__ import annotations

from pathlib import Path

import pandas as pd

from nwb_trace_qc.report import _viewer_start_cmd, render_html


def test_viewer_start_cmd_uses_config_path_when_given():
    assert _viewer_start_cmd("/foo/bar/my_project.yaml") == \
        "nwb-qc serve --config /foo/bar/my_project.yaml"


def test_viewer_start_cmd_falls_back_to_placeholder():
    assert _viewer_start_cmd(None) == "nwb-qc serve --config <your_project_yaml>"
    assert _viewer_start_cmd("") == "nwb-qc serve --config <your_project_yaml>"


def test_rendered_report_carries_start_command_and_handler():
    """The viewer-availability banner is present in the HTML (hidden by default)
    and the _openViewer click handler is wired so a connection failure shows
    the banner instead of letting the browser surface ERR_CONNECTION_REFUSED."""
    df = pd.DataFrame([{
        "cell_id": "c1", "dataset": "ds", "final_verdict": "flag",
        "computed_verdict": "flag", "triggered_metrics": [],
        "vrest_mv": -65.0,
    }])
    html_text = render_html(
        df, thumbnails={},
        project_name="t", pipeline_version="0.6.0",
        config_path="/tmp/marias_project.yaml",
    )
    # Start command is embedded
    assert "nwb-qc serve --config /tmp/marias_project.yaml" in html_text
    # Banner element + JS handlers are present
    assert "id='viewer-banner'" in html_text
    assert "_openViewer" in html_text
    assert "_copyStartCmd" in html_text
    # Both header + per-cell links route through the click handler
    assert "onclick='return _openViewer(event, this)'" in html_text


def test_report_without_config_path_still_shows_placeholder_command():
    """Generated by tooling that doesn't thread config_path (legacy callers)."""
    df = pd.DataFrame([{
        "cell_id": "c1", "dataset": "ds", "final_verdict": "flag",
        "computed_verdict": "flag", "triggered_metrics": [],
    }])
    html_text = render_html(
        df, thumbnails={},
        project_name="t", pipeline_version="0.6.0",
    )
    # HTML-escaped placeholder
    assert "&lt;your_project_yaml&gt;" in html_text
